### ISSUE TITLE
how to find the who create this window

### ISSUE THREAD

**Issue by tw4452852** [nigeltao/taowm#1]
@nigeltao 

Hi Nigel,

I have used your wm for a long time, just amend it slightly for myself. I like it a lot.

Now I encounter a problem sometimes. If I open one application, but it doesn't map its window immediately due some reason. If I change to another workspace now and the new window will belong to the current workspace. This is because in the code, it use the current frame to determine the workspace when a new window map.

But I just want the new window belong to its original workspace that creates it.
I try to use window's parent but it's not the key... Do you have some ideas?

Hope I explain clearly, It just like follow:

in workspace A: sleep 10 && startNewWindow
and I transfer to workspace B
then the new window is located in workspace B, but this is not expected...

**Comment by nigeltao** [comment]
On Thu, Dec 10, 2015 at 12:38 AM, Tw notifications@github.com wrote:

> But I just want the new window belong to its original workspace that creates it.
> I try to use window's parent but it's not the key... Do you have some ideas?

I'd love to be proven wrong, but I don't think this is fixable
(without changing X11 or ICCCM conventions). The window manager
(taowm) only sees the window when it is mapped, which is done by
startNewWindow, not by the shell that ran "sleep 10 &&
startNewWindow". By that point, there's no way, as far as I know, to
tell that that window's heritage can be traced back to the xterm (or
equivalent) in workspace A.

**Comment by driusan** [comment]
It's not ideal, but can't you check the parent pid of the process and follow up the chain until you find a process that you know about?

I just tried on the command line to see how feasable that would be, and it seems like it would work:

```
[2]+  Stopped                 top
driusan@sandman:~$ bg
[2]+ top &
driusan@sandman:~$ ps
  PID TTY          TIME CMD
23210 pts/0    00:00:00 bash
23355 pts/0    00:00:00 top
23410 pts/0    00:00:00 ps

[2]+  Stopped                 top
driusan@sandman:~$ ps -o ppid= -p 23355
23210
driusan@sandman:~$ ps aux | grep "23210"
driusan  23210  0.0  0.0  23564  5644 pts/0    Ss   19:11   0:00 bash
driusan  23413  0.0  0.0  12732  2160 pts/0    S+   19:23   0:00 grep 23210
driusan@sandman:~$ ps -o ppid= -p 23210
23208
driusan@sandman:~$ ps aux | grep "23208"
driusan  23208  0.0  0.1  77500  9908 tty1     S    19:11   0:00 xterm
```

If you follow the chain and don't find something you know about, you can fall back on the default behaviour.

(this has been one of my pet peeves about tabbed window managers for a long time, so I'm sad to hear it's a limitation of X11 since it means I can't just write a patch to fix it..)

**Comment by nigeltao** [comment]
I suppose you could use the _NET_WM_PID mechanism to get the PID of an X window, although not all windows will have that; the application has to opt-in to that convention.

Even so, it could be interesting to try, but it doesn't seem foolproof. Some programs are started by Caps Lock + Space instead of from an xterm. Some programs like web browsers, text editors and terminal emulators don't map 1:1 between processes and windows. On my system right now, I have only one "gnome-terminal" process for multiple windows on multiple workspaces.

Walking up the PID chain might end up being too unreliable and unpredictable to be a net win.
