### ISSUE TITLE
Can't get taowm to start.

### ISSUE THREAD

**Issue by driusan** [nigeltao/taowm#3]
I'm trying to see how taowm compares to awesome or ion, and I can't seem to get it to start. When I add it to the end of my .xsession, it immediately quit with no error message and nothing obvious in the X server logs. I've tried putting it in a menu option and to it from pwm in the same way that other WMs are options that can be switched to (and work), but again, it seems to just quit back to the terminal. No panic, no error message, nothing. It seems like it's just exiting (and then X is exiting as a result.)

It's not very helpful, but this is my .xsession file, since I can't find any other useful information (both the rio and pwm options work.)

```
PLAN9=/usr/local/plan9 export PLAN9
GOPATH=/home/driusan/Code/Go
PATH=$PATH:$PLAN9/bin:$GOPATH/bin export PATH

xmodmap ~/.Xmodmap
xclock -geom 128x128-0+0&
# exec rio
# exec pwm
/home/driusan/Code/Go/bin/taowm
```

**Comment by nigeltao** [comment]
Huh. Nothing in "~/.xsession-errors"??

What happens if you log into an orthodox desktop environment, like GNOME, and then try to run taowm from the command line?

Apart from that, I don't really have any leads, other than suggesting you add some printf debugging to taowm (probably to stderr instead of stdout), sorry.

**Comment by driusan** [comment]
I had missed the line in ~/.xsession-errors, I was just looking in /var/log/Xorg. It turns out it was because my xmodmap already mapped caps-lock to ctrl, and it was dying because it couldn't find the caps lock key.
